"""LLM-generated initial annotations for BWOR. REVIEW REQUIRED.

Generated by reading each en_question and classifying along two axes:

  domain (9 categories):
    production_planning  manufacturing decisions under resource constraints
    transportation       shipping goods between sources and destinations
    assignment           matching agents to tasks one-to-one or one-to-many
    scheduling           sequencing jobs or shifts in time (incl. staff scheduling)
    blending             mixing materials under proportional constraints
    inventory            multi-period purchase / storage / sale
    network              graph-based problems (TSP, MST, shortest path, PERT/CPM)
    finance              investment, cash-flow, capital budgeting
    resource_allocation  knapsack, facility location, generic allocation

  problem_type (5 categories):
    LP                   linear programming, all continuous
    IP                   pure integer programming (incl. binary)
    MIP                  mixed integer programming
    NLP                  nonlinear objective or constraint
    goal_programming     preemptive priority goal programming

These are FIRST-PASS annotations. Edge cases:
  * id 13, 14: explicit goal programming structure -> goal_programming
  * id 21, 59, 66, 70, 71: nonlinear (log, Euclidean, quadratic) -> NLP
  * id 36, 53: BWOR labels these "No Best Solution"; classification is by
    structural type ignoring feasibility status
  * Several "DP textbook" problems (id 20, 60, 61, 62, 63, 72, 75) are
    classified by their decision-variable type (IP), not by solution method
"""

ANNOTATIONS = {
    0:  {"domain": "blending",            "problem_type": "LP"},   # candy raw materials A/B/C -> 3 brands
    1:  {"domain": "blending",            "problem_type": "LP"},   # animal feed nutrition mix
    2:  {"domain": "finance",             "problem_type": "LP"},   # multi-year loan / bond investment
    3:  {"domain": "production_planning", "problem_type": "MIP"},  # garment + worker hire (integer workers)
    4:  {"domain": "resource_allocation", "problem_type": "LP"},   # cargo ship 3 compartments x 3 cargo types
    5:  {"domain": "production_planning", "problem_type": "LP"},   # 3 products on machines A1/A2 + B1/B2/B3
    6:  {"domain": "finance",             "problem_type": "LP"},   # toy factory cash flow + loans
    7:  {"domain": "transportation",      "problem_type": "IP"},   # min ships across shipping routes
    8:  {"domain": "inventory",           "problem_type": "LP"},   # quarterly equipment delivery + storage
    9:  {"domain": "transportation",      "problem_type": "LP"},   # flour mills -> food factories
    10: {"domain": "transportation",      "problem_type": "LP"},   # 2 power stations -> 3 cities
    11: {"domain": "blending",            "problem_type": "LP"},   # liquor 3 brands x 3 grades blending
    12: {"domain": "finance",             "problem_type": "LP"},   # fund allocation across 3 products
    13: {"domain": "blending",            "problem_type": "goal_programming"},  # milk/beef/eggs goal program
    14: {"domain": "production_planning", "problem_type": "goal_programming"},  # 3 products 3 stages goal program
    15: {"domain": "resource_allocation", "problem_type": "MIP"},  # facility location A3/A4 build + transport
    16: {"domain": "production_planning", "problem_type": "MIP"},  # 3 products with fixed-charge organization cost
    17: {"domain": "assignment",          "problem_type": "IP"},   # 5 stores x 5 construction companies
    18: {"domain": "assignment",          "problem_type": "IP"},   # basketball 5 of 8 with logical conditions
    19: {"domain": "transportation",      "problem_type": "IP"},   # truck delivery set-covering
    20: {"domain": "finance",             "problem_type": "IP"},   # 3 projects discrete-fund allocation
    21: {"domain": "resource_allocation", "problem_type": "NLP"},  # spare parts log-reliability product
    22: {"domain": "network",             "problem_type": "IP"},   # TSP 4 cities
    23: {"domain": "scheduling",          "problem_type": "IP"},   # 6 jobs A->B (Johnson)
    24: {"domain": "scheduling",          "problem_type": "IP"},   # 12 jobs A->B
    25: {"domain": "scheduling",          "problem_type": "IP"},   # 12 jobs split A->B / B->A
    26: {"domain": "network",             "problem_type": "IP"},   # TSP 10 cities
    27: {"domain": "scheduling",          "problem_type": "IP"},   # hospital 6-shift nurse scheduling
    28: {"domain": "scheduling",          "problem_type": "IP"},   # hospital full-time + contract nurses
    29: {"domain": "inventory",           "problem_type": "LP"},   # grain warehouse 1Q purchase/sale
    30: {"domain": "production_planning", "problem_type": "MIP"},  # farm crops + dairy + chickens (integer animals)
    31: {"domain": "production_planning", "problem_type": "LP"},   # products I/II monthly with volume
    32: {"domain": "production_planning", "problem_type": "LP"},   # quarterly product orders + hours
    33: {"domain": "inventory",           "problem_type": "MIP"},  # warehouse rental contract durations
    34: {"domain": "resource_allocation", "problem_type": "IP"},   # bombers fuel + heavy/light bombs
    35: {"domain": "inventory",           "problem_type": "LP"},   # timber quarterly purchase/sale + storage cost
    36: {"domain": "scheduling",          "problem_type": "IP"},   # technicians+laborers for 3 tasks (no_optimal)
    37: {"domain": "production_planning", "problem_type": "LP"},   # Hongsheng 3 products x A/B machines
    38: {"domain": "production_planning", "problem_type": "LP"},   # cultural supplies paper allocation
    39: {"domain": "production_planning", "problem_type": "LP"},   # same as 38 variant
    40: {"domain": "transportation",      "problem_type": "LP"},   # toy supply 3 stores
    41: {"domain": "transportation",      "problem_type": "LP"},   # 3 origins x 5 destinations
    42: {"domain": "transportation",      "problem_type": "LP"},   # 4 origins x 6 destinations
    43: {"domain": "transportation",      "problem_type": "LP"},   # transportation + origin storage cost
    44: {"domain": "transportation",      "problem_type": "LP"},   # chemical 4 plants x 6 regions
    45: {"domain": "transportation",      "problem_type": "LP"},   # transshipment via 3 warehouses
    46: {"domain": "production_planning", "problem_type": "MIP"},  # shipyard 3yr normal/overtime
    47: {"domain": "inventory",           "problem_type": "IP"},   # engine replacement new/repaired
    48: {"domain": "transportation",      "problem_type": "LP"},   # 2 origins -> 3 destinations w/ transshipment
    49: {"domain": "assignment",          "problem_type": "IP"},   # 5 swimmers x 4 strokes relay
    50: {"domain": "assignment",          "problem_type": "IP"},   # 4 people x 5 tasks 3 scenarios
    51: {"domain": "production_planning", "problem_type": "MIP"},  # 4 machines fixed setup + variable cost
    52: {"domain": "scheduling",          "problem_type": "LP"},   # student lab Q&A duty hours
    53: {"domain": "scheduling",          "problem_type": "LP"},   # variant of 52 (no_optimal)
    54: {"domain": "production_planning", "problem_type": "MIP"},  # 3 specialized equipment fixed cost
    55: {"domain": "assignment",          "problem_type": "IP"},   # course selection 3 categories
    56: {"domain": "production_planning", "problem_type": "MIP"},  # 6 plastic containers fixed machine cost
    57: {"domain": "resource_allocation", "problem_type": "IP"},   # mall lease 5 store types per-count profit
    58: {"domain": "production_planning", "problem_type": "MIP"},  # auto batches semicontinuous (>=1000 or 0)
    59: {"domain": "resource_allocation", "problem_type": "NLP"},  # village school Euclidean facility location
    60: {"domain": "scheduling",          "problem_type": "IP"},   # 3 candidates sequential interview
    61: {"domain": "resource_allocation", "problem_type": "IP"},   # 4 outlets x 3 regions DP-table
    62: {"domain": "resource_allocation", "problem_type": "IP"},   # 2 resources x 3 departments DP-table
    63: {"domain": "resource_allocation", "problem_type": "IP"},   # 3 factories x discrete renovation plans
    64: {"domain": "production_planning", "problem_type": "MIP"},  # T factory monthly production + fixed/storage
    65: {"domain": "inventory",           "problem_type": "IP"},   # store 4-month purchase/sale (integer units)
    66: {"domain": "production_planning", "problem_type": "NLP"},  # 3-month production with quadratic cost x^2
    67: {"domain": "inventory",           "problem_type": "IP"},   # snow boots 6-month order quantities
    68: {"domain": "resource_allocation", "problem_type": "IP"},   # 3-product knapsack 10 tons
    69: {"domain": "resource_allocation", "problem_type": "IP"},   # 4-item knapsack weight + volume
    70: {"domain": "production_planning", "problem_type": "NLP"},  # price = a - b*x quadratic revenue
    71: {"domain": "resource_allocation", "problem_type": "NLP"},  # E1/E2/E3 reliability product
    72: {"domain": "resource_allocation", "problem_type": "IP"},   # 12 patrol units x 4 warehouses
    73: {"domain": "scheduling",          "problem_type": "IP"},   # exam grade sort sequencing
    74: {"domain": "network",             "problem_type": "IP"},   # 8 oil wells minimum spanning tree
    75: {"domain": "inventory",           "problem_type": "IP"},   # 4-year machine replacement
    76: {"domain": "assignment",          "problem_type": "IP"},   # assembly line 5 workers x 5 stations
    77: {"domain": "network",             "problem_type": "LP"},   # garage CPM/PERT critical path
    78: {"domain": "scheduling",          "problem_type": "IP"},   # 5 shifts x 7 days nurse roster
    79: {"domain": "production_planning", "problem_type": "LP"},   # 5 machine types x 7 products
    80: {"domain": "production_planning", "problem_type": "LP"},   # 2 pastries x 2 raw materials
    81: {"domain": "resource_allocation", "problem_type": "IP"},   # 5 workshops relocate to 2 satellite towns
}

assert len(ANNOTATIONS) == 82, f"expected 82 annotations, got {len(ANNOTATIONS)}"
assert all(isinstance(k, int) and 0 <= k <= 81 for k in ANNOTATIONS), "ids must be 0..81"

_DOMAINS = {
    "production_planning", "transportation", "assignment", "scheduling",
    "blending", "inventory", "network", "finance", "resource_allocation",
}
_TYPES = {"LP", "IP", "MIP", "NLP", "goal_programming"}

for _id, _ann in ANNOTATIONS.items():
    assert _ann["domain"] in _DOMAINS, f"id {_id} unknown domain {_ann['domain']!r}"
    assert _ann["problem_type"] in _TYPES, f"id {_id} unknown problem_type {_ann['problem_type']!r}"
